[project]
name = "optic-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tenglon", email = "uestc.longteng@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "nvidia-cuda-nvcc>=13.3.73",
    "opencv-contrib-python-headless>=5.0.0.93",
    "torch>=2.13.0",
]

[project.scripts]
optic-flow = "optic_flow:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
